pipeline {
    agent any

    stages {

        stage('Test Gudang') {
            steps {
                dir('TUBES/logistik-microservice-final/gudang-service') {
                    sh 'go test ./...'
                }
            }
        }

        stage('Test Courier') {
            steps {
                dir('TUBES/logistik-microservice-final/courier-service') {
                    sh 'go test ./...'
                }
            }
        }

        stage('Build Images') {
            steps {
                dir('TUBES/logistik-microservice-final') {
                    sh 'docker compose build'
                }
            }
        }

        stage('Run Containers') {
            steps {
                dir('TUBES/logistik-microservice-final') {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Verify') {
            steps {
                sh 'curl http://localhost:8085/packages'
                sh 'curl http://localhost:8086/deliveries'
            }
        }
    }
}